/**
 * This class is generated by jOOQ
 */
package sxj.db.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import sxj.db.tables.AdminUser;
import sxj.db.tables.records.AdminUserRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class AdminUserDao extends DAOImpl<AdminUserRecord, sxj.db.tables.pojos.AdminUser, Integer> {

    /**
     * Create a new AdminUserDao without any configuration
     */
    public AdminUserDao() {
        super(AdminUser.ADMIN_USER, sxj.db.tables.pojos.AdminUser.class);
    }

    /**
     * Create a new AdminUserDao with an attached configuration
     */
    @Autowired
    public AdminUserDao(Configuration configuration) {
        super(AdminUser.ADMIN_USER, sxj.db.tables.pojos.AdminUser.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(sxj.db.tables.pojos.AdminUser object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<sxj.db.tables.pojos.AdminUser> fetchByUsername(String... values) {
        return fetch(AdminUser.ADMIN_USER.USERNAME, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<sxj.db.tables.pojos.AdminUser> fetchByPassword(String... values) {
        return fetch(AdminUser.ADMIN_USER.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<sxj.db.tables.pojos.AdminUser> fetchById(Integer... values) {
        return fetch(AdminUser.ADMIN_USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public sxj.db.tables.pojos.AdminUser fetchOneById(Integer value) {
        return fetchOne(AdminUser.ADMIN_USER.ID, value);
    }
}
