/**
 * This class is generated by jOOQ
 */
package sxj.db.tables.daos;


import java.util.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import sxj.db.tables.Appointment;
import sxj.db.tables.records.AppointmentRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class AppointmentDao extends DAOImpl<AppointmentRecord, sxj.db.tables.pojos.Appointment, Integer> {

    /**
     * Create a new AppointmentDao without any configuration
     */
    public AppointmentDao() {
        super(Appointment.APPOINTMENT, sxj.db.tables.pojos.Appointment.class);
    }

    /**
     * Create a new AppointmentDao with an attached configuration
     */
    @Autowired
    public AppointmentDao(Configuration configuration) {
        super(Appointment.APPOINTMENT, sxj.db.tables.pojos.Appointment.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(sxj.db.tables.pojos.Appointment object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<sxj.db.tables.pojos.Appointment> fetchById(Integer... values) {
        return fetch(Appointment.APPOINTMENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public sxj.db.tables.pojos.Appointment fetchOneById(Integer value) {
        return fetchOne(Appointment.APPOINTMENT.ID, value);
    }

    /**
     * Fetch records that have <code>context IN (values)</code>
     */
    public List<sxj.db.tables.pojos.Appointment> fetchByContext(String... values) {
        return fetch(Appointment.APPOINTMENT.CONTEXT, values);
    }

    /**
     * Fetch records that have <code>money IN (values)</code>
     */
    public List<sxj.db.tables.pojos.Appointment> fetchByMoney(Double... values) {
        return fetch(Appointment.APPOINTMENT.MONEY, values);
    }

    /**
     * Fetch records that have <code>flag IN (values)</code>
     */
    public List<sxj.db.tables.pojos.Appointment> fetchByFlag(Integer... values) {
        return fetch(Appointment.APPOINTMENT.FLAG, values);
    }

    /**
     * Fetch records that have <code>vip_id IN (values)</code>
     */
    public List<sxj.db.tables.pojos.Appointment> fetchByVipId(Integer... values) {
        return fetch(Appointment.APPOINTMENT.VIP_ID, values);
    }

    /**
     * Fetch records that have <code>appoint_time IN (values)</code>
     */
    public List<sxj.db.tables.pojos.Appointment> fetchByAppointTime(Date... values) {
        return fetch(Appointment.APPOINTMENT.APPOINT_TIME, values);
    }
}
