/**
 * This class is generated by jOOQ
 */
package sxj.db.tables.daos;


import java.util.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import sxj.db.tables.ConsumptionRecord;
import sxj.db.tables.records.ConsumptionRecordRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ConsumptionRecordDao extends DAOImpl<ConsumptionRecordRecord, sxj.db.tables.pojos.ConsumptionRecord, Integer> {

    /**
     * Create a new ConsumptionRecordDao without any configuration
     */
    public ConsumptionRecordDao() {
        super(ConsumptionRecord.CONSUMPTION_RECORD, sxj.db.tables.pojos.ConsumptionRecord.class);
    }

    /**
     * Create a new ConsumptionRecordDao with an attached configuration
     */
    @Autowired
    public ConsumptionRecordDao(Configuration configuration) {
        super(ConsumptionRecord.CONSUMPTION_RECORD, sxj.db.tables.pojos.ConsumptionRecord.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(sxj.db.tables.pojos.ConsumptionRecord object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<sxj.db.tables.pojos.ConsumptionRecord> fetchById(Integer... values) {
        return fetch(ConsumptionRecord.CONSUMPTION_RECORD.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public sxj.db.tables.pojos.ConsumptionRecord fetchOneById(Integer value) {
        return fetchOne(ConsumptionRecord.CONSUMPTION_RECORD.ID, value);
    }

    /**
     * Fetch records that have <code>money IN (values)</code>
     */
    public List<sxj.db.tables.pojos.ConsumptionRecord> fetchByMoney(Double... values) {
        return fetch(ConsumptionRecord.CONSUMPTION_RECORD.MONEY, values);
    }

    /**
     * Fetch records that have <code>time IN (values)</code>
     */
    public List<sxj.db.tables.pojos.ConsumptionRecord> fetchByTime(Date... values) {
        return fetch(ConsumptionRecord.CONSUMPTION_RECORD.TIME, values);
    }

    /**
     * Fetch records that have <code>context IN (values)</code>
     */
    public List<sxj.db.tables.pojos.ConsumptionRecord> fetchByContext(String... values) {
        return fetch(ConsumptionRecord.CONSUMPTION_RECORD.CONTEXT, values);
    }

    /**
     * Fetch records that have <code>vip_id IN (values)</code>
     */
    public List<sxj.db.tables.pojos.ConsumptionRecord> fetchByVipId(Integer... values) {
        return fetch(ConsumptionRecord.CONSUMPTION_RECORD.VIP_ID, values);
    }
}
