/**
 * This class is generated by jOOQ
 */
package sxj.db.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import sxj.db.tables.VipUser;
import sxj.db.tables.records.VipUserRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class VipUserDao extends DAOImpl<VipUserRecord, sxj.db.tables.pojos.VipUser, Integer> {

    /**
     * Create a new VipUserDao without any configuration
     */
    public VipUserDao() {
        super(VipUser.VIP_USER, sxj.db.tables.pojos.VipUser.class);
    }

    /**
     * Create a new VipUserDao with an attached configuration
     */
    @Autowired
    public VipUserDao(Configuration configuration) {
        super(VipUser.VIP_USER, sxj.db.tables.pojos.VipUser.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(sxj.db.tables.pojos.VipUser object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<sxj.db.tables.pojos.VipUser> fetchById(Integer... values) {
        return fetch(VipUser.VIP_USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public sxj.db.tables.pojos.VipUser fetchOneById(Integer value) {
        return fetchOne(VipUser.VIP_USER.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<sxj.db.tables.pojos.VipUser> fetchByName(String... values) {
        return fetch(VipUser.VIP_USER.NAME, values);
    }

    /**
     * Fetch records that have <code>age IN (values)</code>
     */
    public List<sxj.db.tables.pojos.VipUser> fetchByAge(Integer... values) {
        return fetch(VipUser.VIP_USER.AGE, values);
    }

    /**
     * Fetch records that have <code>telephone IN (values)</code>
     */
    public List<sxj.db.tables.pojos.VipUser> fetchByTelephone(String... values) {
        return fetch(VipUser.VIP_USER.TELEPHONE, values);
    }

    /**
     * Fetch records that have <code>integrate IN (values)</code>
     */
    public List<sxj.db.tables.pojos.VipUser> fetchByIntegrate(Integer... values) {
        return fetch(VipUser.VIP_USER.INTEGRATE, values);
    }

    /**
     * Fetch records that have <code>level IN (values)</code>
     */
    public List<sxj.db.tables.pojos.VipUser> fetchByLevel(Integer... values) {
        return fetch(VipUser.VIP_USER.LEVEL, values);
    }

    /**
     * Fetch records that have <code>sex IN (values)</code>
     */
    public List<sxj.db.tables.pojos.VipUser> fetchBySex(Integer... values) {
        return fetch(VipUser.VIP_USER.SEX, values);
    }

    /**
     * Fetch records that have <code>money IN (values)</code>
     */
    public List<sxj.db.tables.pojos.VipUser> fetchByMoney(Double... values) {
        return fetch(VipUser.VIP_USER.MONEY, values);
    }
}
