/**
 * This class is generated by jOOQ
 */
package sxj.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import sxj.db.tables.CodeMessage;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CodeMessageRecord extends UpdatableRecordImpl<CodeMessageRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -679295216;

    /**
     * Setter for <code>barbershopvip.code_message.code</code>.
     */
    public CodeMessageRecord setCode(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>barbershopvip.code_message.code</code>.
     */
    public Integer getCode() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>barbershopvip.code_message.message</code>.
     */
    public CodeMessageRecord setMessage(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>barbershopvip.code_message.message</code>.
     */
    public String getMessage() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CodeMessage.CODE_MESSAGE.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CodeMessage.CODE_MESSAGE.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CodeMessageRecord value1(Integer value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CodeMessageRecord value2(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CodeMessageRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CodeMessageRecord
     */
    public CodeMessageRecord() {
        super(CodeMessage.CODE_MESSAGE);
    }

    /**
     * Create a detached, initialised CodeMessageRecord
     */
    public CodeMessageRecord(Integer code, String message) {
        super(CodeMessage.CODE_MESSAGE);

        set(0, code);
        set(1, message);
    }
}
