/**
 * This class is generated by jOOQ
 */
package sxj.db.tables.records;


import java.util.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import sxj.db.tables.ConsumptionRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConsumptionRecordRecord extends UpdatableRecordImpl<ConsumptionRecordRecord> implements Record5<Integer, Double, Date, String, Integer> {

    private static final long serialVersionUID = -2128347731;

    /**
     * Setter for <code>barbershopvip.consumption_record.id</code>.
     */
    public ConsumptionRecordRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>barbershopvip.consumption_record.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>barbershopvip.consumption_record.money</code>. 消费金额
     */
    public ConsumptionRecordRecord setMoney(Double value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>barbershopvip.consumption_record.money</code>. 消费金额
     */
    public Double getMoney() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>barbershopvip.consumption_record.time</code>. 消费时间
     */
    public ConsumptionRecordRecord setTime(Date value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>barbershopvip.consumption_record.time</code>. 消费时间
     */
    public Date getTime() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>barbershopvip.consumption_record.context</code>. 具体消费
     */
    public ConsumptionRecordRecord setContext(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>barbershopvip.consumption_record.context</code>. 具体消费
     */
    public String getContext() {
        return (String) get(3);
    }

    /**
     * Setter for <code>barbershopvip.consumption_record.vip_id</code>. vip主键
     */
    public ConsumptionRecordRecord setVipId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>barbershopvip.consumption_record.vip_id</code>. vip主键
     */
    public Integer getVipId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Double, Date, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Double, Date, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ConsumptionRecord.CONSUMPTION_RECORD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field2() {
        return ConsumptionRecord.CONSUMPTION_RECORD.MONEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return ConsumptionRecord.CONSUMPTION_RECORD.TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ConsumptionRecord.CONSUMPTION_RECORD.CONTEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return ConsumptionRecord.CONSUMPTION_RECORD.VIP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value2() {
        return getMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getContext();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getVipId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsumptionRecordRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsumptionRecordRecord value2(Double value) {
        setMoney(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsumptionRecordRecord value3(Date value) {
        setTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsumptionRecordRecord value4(String value) {
        setContext(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsumptionRecordRecord value5(Integer value) {
        setVipId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConsumptionRecordRecord values(Integer value1, Double value2, Date value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConsumptionRecordRecord
     */
    public ConsumptionRecordRecord() {
        super(ConsumptionRecord.CONSUMPTION_RECORD);
    }

    /**
     * Create a detached, initialised ConsumptionRecordRecord
     */
    public ConsumptionRecordRecord(Integer id, Double money, Date time, String context, Integer vipId) {
        super(ConsumptionRecord.CONSUMPTION_RECORD);

        set(0, id);
        set(1, money);
        set(2, time);
        set(3, context);
        set(4, vipId);
    }
}
