/**
 * This class is generated by jOOQ
 */
package sxj.db;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import sxj.db.tables.AdminUser;
import sxj.db.tables.Appointment;
import sxj.db.tables.CodeMessage;
import sxj.db.tables.ConsumptionRecord;
import sxj.db.tables.VipUser;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Barbershopvip extends SchemaImpl {

    private static final long serialVersionUID = -344205352;

    /**
     * The reference instance of <code>barbershopvip</code>
     */
    public static final Barbershopvip BARBERSHOPVIP = new Barbershopvip();

    /**
     * The table <code>barbershopvip.admin_user</code>.
     */
    public final AdminUser ADMIN_USER = sxj.db.tables.AdminUser.ADMIN_USER;

    /**
     * The table <code>barbershopvip.appointment</code>.
     */
    public final Appointment APPOINTMENT = sxj.db.tables.Appointment.APPOINTMENT;

    /**
     * The table <code>barbershopvip.code_message</code>.
     */
    public final CodeMessage CODE_MESSAGE = sxj.db.tables.CodeMessage.CODE_MESSAGE;

    /**
     * The table <code>barbershopvip.consumption_record</code>.
     */
    public final ConsumptionRecord CONSUMPTION_RECORD = sxj.db.tables.ConsumptionRecord.CONSUMPTION_RECORD;

    /**
     * The table <code>barbershopvip.vip_user</code>.
     */
    public final VipUser VIP_USER = sxj.db.tables.VipUser.VIP_USER;

    /**
     * No further instances allowed
     */
    private Barbershopvip() {
        super("barbershopvip", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AdminUser.ADMIN_USER,
            Appointment.APPOINTMENT,
            CodeMessage.CODE_MESSAGE,
            ConsumptionRecord.CONSUMPTION_RECORD,
            VipUser.VIP_USER);
    }
}
