/**
 * This class is generated by jOOQ
 */
package sxj.db;


import javax.annotation.Generated;

import sxj.db.tables.AdminUser;
import sxj.db.tables.Appointment;
import sxj.db.tables.CodeMessage;
import sxj.db.tables.ConsumptionRecord;
import sxj.db.tables.VipUser;


/**
 * Convenience access to all tables in barbershopvip
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>barbershopvip.admin_user</code>.
     */
    public static final AdminUser ADMIN_USER = sxj.db.tables.AdminUser.ADMIN_USER;

    /**
     * The table <code>barbershopvip.appointment</code>.
     */
    public static final Appointment APPOINTMENT = sxj.db.tables.Appointment.APPOINTMENT;

    /**
     * The table <code>barbershopvip.code_message</code>.
     */
    public static final CodeMessage CODE_MESSAGE = sxj.db.tables.CodeMessage.CODE_MESSAGE;

    /**
     * The table <code>barbershopvip.consumption_record</code>.
     */
    public static final ConsumptionRecord CONSUMPTION_RECORD = sxj.db.tables.ConsumptionRecord.CONSUMPTION_RECORD;

    /**
     * The table <code>barbershopvip.vip_user</code>.
     */
    public static final VipUser VIP_USER = sxj.db.tables.VipUser.VIP_USER;
}
